# Generated by Django 4.1.4 on 2023-04-08 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='amount',
            new_name='age',
        ),
    ]
